### ISSUE TITLE
Identische Dateien

### ISSUE THREAD

**Issue by SamNitro** [nortakales/flipper-zero-tonies#15]
Hey super arbeit die du / ihr macht...
Mir ist aufgefallen das,
->German/Disney/Die Schoene und das Biest.nfc
->German/Disney/Dornroeschen.nfc
die selben dateien sind.
Gruß Patrick

**Comment by deathduck666** [comment]
Hey Patrick,

Danke für den Hinweis. Dornroeschen.nfc ist jetzt korrigiert.


@nortakales This Issue is done as well. Pull request for changed file is created.
