### ISSUE TITLE
Toy Story 2

### ISSUE THREAD

**Issue by SamNitro** [nortakales/flipper-zero-tonies#40]
Hey,
German/Disney/Toy Story 2.nfc ist fehlerhaft.

Gruß Patrick

**Comment by knonymous83** [comment]
Hi, gerade gecheckt und die hier hinterlegte Datei ist tatsächlich fehlerhaft. Mein Original geht aber. Ich lade später erneut hoch

**Comment by nortakales** [comment]
Sorry, don't speak German!

We'll need a new upload. It looks like a chunk of the file is actually missing.

I should implement some kind of validation in this repo. This kind of thing could be validated automatically (at least that all the correct fields are present).

**Comment by SamNitro** [comment]
Okay, thanks for your great work.

**Comment by knonymous83** [comment]
Hi, yeah I noticed that something is wrong with the uploaded info. I will correct that asap, but I noticed that I accidentally deleted my original file. I will rescan it asap.

**Comment by knonymous83** [comment]
I have just updated the file and created a pull request.

**Comment by deathduck666** [comment]
Corrected file works without any problems. Thanks for correction!
@nortakales Issue can be closed
