### ISSUE TITLE
What Firmware for emulation

### ISSUE THREAD

**Issue by Fabunator** [nortakales/flipper-zero-tonies#61]
Hi i just wanted to ask which firmware you are using for emulating the tonies.

I use Momentum and the emulation stops after a coupple of minutes because flipper crashes and i have to start again.

Is there any firmware capable of emulating a whole tonie

**Comment by deathduck666** [comment]
I`m using unlshd 077e without any problems
Sometimes it emulates whole night

**Comment by nortakales** [comment]
Official firmware has never given me problems, but I don't think I've emulated past about 30 minutes.

**Comment by knonymous83** [comment]
I am running official stable release only. Works fine if bluetooth is disabled for hours. With active bluetooth the f0 crashes occasionally.
